SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3

ASTEROID_SPAWN_RATE = .1
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20

PLAYER_TURN_SPEED = 300

PLAYER_SHOOT_SPEED = 750
PLAYER_SHOOT_COOLDOWN = .1
PLAYER_MAX_SPEED = 5000
PLAYER_ACCELERATION = 2500
PLAYER_FRICTION = .99
SHOT_RADIUS = 3




WORLD_WIDTH = 9600
WORLD_HEIGHT = 5400