SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 5
ASTEROID_SPAWN_RATE = 3
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20

PLAYER_TURN_SPEED = 300

PLAYER_SHOOT_SPEED = 750
PLAYER_SHOOT_COOLDOWN = .1
PLAYER_MAX_SPEED = 250
PLAYER_ACCELERATION = 250
PLAYER_FRICTION = .99
SHOT_RADIUS = 3
